#' @description DATASET_DESCRIPTION
#' @format A data frame with 34 rows and 166 variables:
#' \describe{
#'   \item{\code{...1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hunting_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hunting_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{honey_m_rater1_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respected_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respected_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{respect_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{fighting_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{expertise_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{control_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{intelligent_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{likable_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{feared_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{spouse_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{parenting_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_m_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{kin_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_f_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hunting_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_f_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{decisions_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{conflict_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{allies_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_m_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prosocial_f_rater5_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{honey_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{coffee_m_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hunting_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hunting_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{honey_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{honey_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{coffee_m_rater7_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_f_rater2_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{coffee_m_rater6_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_f_rater3_male}}{double COLUMN_DESCRIPTION}
#'   \item{\code{farming_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{honey_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{coffee_m_rater4_female}}{double COLUMN_DESCRIPTION}
#'   \item{\code{coffee_m_rater2_male}}{double COLUMN_DESCRIPTION}
#'}
#' @source \url{http://somewhere.important.com/}
"chaburankingsdata"

#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 60 rows and 9 variables:
#' \describe{
#'   \item{\code{date}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time}}{double COLUMN_DESCRIPTION}
#'   \item{\code{id}}{double COLUMN_DESCRIPTION}
#'   \item{\code{sex}}{character COLUMN_DESCRIPTION}
#'   \item{\code{age_category}}{character COLUMN_DESCRIPTION}
#'   \item{\code{age_estimated}}{double COLUMN_DESCRIPTION}
#'   \item{\code{height}}{double COLUMN_DESCRIPTION}
#'   \item{\code{grip_RH}}{double COLUMN_DESCRIPTION}
#'   \item{\code{grip_LH}}{double COLUMN_DESCRIPTION}
#'}
#' @source \url{http://somewhere.important.com/}
"chaburankingsmetadata"
